# Generated by Django 3.2.8 on 2021-10-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='no shoe type', max_length=100)),
                ('brand_url', models.TextField(default='no brand exist')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='shoes.shoes')),
            ],
        ),
    ]
